portal/urls.py
from django.conf.urls import include, url
from django.views.generic import TemplateView
#nuevo para redirecciones de url
from django.views.generic.base import RedirectView
from portal import views as portal_views

app_name = 'portal'
from .views import HomeView, upload_csv, FuncionaView, contacto, ContactoView, neural, NeuralView, CondicionesView, PrivacidadView, subscribe, successView, contacto


urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),  
        url(r'^how-it-works/$', FuncionaView.as_view(), name='funciona'),
        url(r'^subscribe/', subscribe, name="subscribe"),
        url(r'^contact/', contacto, name='contacto'),
        url(r'^contact/$', ContactoView.as_view(), name='contacto'),
        url(r'^results/$', upload_csv, name='upload_csv'),
        url(r'^deep-learning/$', NeuralView.as_view(), name='neuralview'),
        url(r'^neural-results/$', neural, name= 'neural'),
]

portal/models.py
from django.db import models
from django.utils import timezone
from django.db.models import Count, CharField, Model



class Subscribe(models.Model):
    email_id = models.EmailField(null=True, blank=True)
    timestamp = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.email_id

portal/views.py
# This Python file uses the following encoding in format utf-8
import plotly
import plotly.express as px
import plotly.graph_objects as go
from django.core.mail import send_mail, BadHeaderError, EmailMessage

import io
import csv
from io import BytesIO
import base64
import functools
import operator
import random
import unicodedata
import datetime
import pandas as pd
import seaborn as sns
import numpy as np
from efficient_apriori import apriori

from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

from sklearn.ensemble import RandomForestClassifier
from sklearn.cluster import KMeans
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LinearRegression
from sklearn.naive_bayes import GaussianNB

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.optimizers import RMSprop

from django.template.loader import get_template, render_to_string
from django.shortcuts import render
from django.views.generic import TemplateView
from django.views.generic.detail import DetailView
from django.views import View
from django.db.models import Count
from django.shortcuts import redirect

from portal.models import Subscribe

from el_pagination.views import AjaxListView
from django.http import Http404, JsonResponse, HttpResponse, HttpResponseRedirect, HttpResponseServerError
from django.db.models import Q
from django.contrib.staticfiles.templatetags.staticfiles import static
 
class HomeView(View):
    def get(self, request, *args, **kwargs):
        context={}
        context['is_home'] = True
        context['lazyjs'] = True
        context['valoracionesjs'] = False
        context['valoracionesTiendajs'] = False
        context['normal_footer_cat'] = True

        return render(request, 'portal.html', context)


class ContactoView(View):

    def get(self, request, *args, **kwargs):
        context={}
        context['is_home'] = False
        context['lazyjs'] = False
        context['valoracionesjs'] = False
        context['valoracionesTiendajs'] = False
        context['normal_footer_cat'] = True
        return render(request, 'contacto.html', context)


class PrivacidadView(View):

     def get(self, request, *args, **kwargs):
        context={}
        context['is_home'] = False
        context['lazyjs'] = False
        context['valoracionesjs'] = False
        context['valoracionesTiendajs'] = False
        context['normal_footer_cat'] = True

        return render(request, 'priv.html', context)


       
def contacto(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        email = request.POST.get('email_contacto')
        message = request.POST.get('message')
        
        body = render_to_string(
            'email_content.html', {
                'name': name,
                'email': email,
                'message': message,
            },
        )

        if name and message and email:
            try:
                #email_message.send()
                send_mail('Trainyourmodel :: Formulario Web', body, 'dirusali@gmail.com', ['dirusali@gmail.com'])
                send_mail('Trainyourmodel', 'Your email was sent, I will try to respond asap', 'dirusali@gmail.com', [email])
            except BadHeaderError:
                return HttpResponse('Invalid header found.')
            return HttpResponseRedirect('/message-sent/')
        else:
            # In reality we'd use a form class
            # to get proper validation errors.
            return HttpResponse('Please check you filled all fields correctly.')
    else:
        context={}
        context['is_home'] = False
        context['lazyjs'] = False
        context['valoracionesjs'] = False
        context['valoracionesTiendajs'] = False
        context['normal_footer_cat'] = True
        current_anno = datetime.datetime.now().strftime('%Y')
        context['current_anno'] = current_anno
        
        return render(request, 'contacto.html', context)      


		
def successView(request):
    context={}
    context['is_home'] = True
    context['lazyjs'] = False
    context['valoracionesjs'] = False
    context['valoracionesTiendajs'] = False
    context['normal_footer_cat'] = True

    return render(request, 'success.html', context)
       
class FuncionaView(View):

    def get(self, request, *args, **kwargs):
        context={}
        context['is_home'] = False
        context['lazyjs'] = False
        context['valoracionesjs'] = False
        context['valoracionesTiendajs'] = False
        context['normal_footer_cat'] = True

        return render(request, 'funciona.html', context)
	
class NeuralView(View):

    def get(self, request, *args, **kwargs):
        context={}
        context['is_home'] = False
        context['lazyjs'] = False
        context['valoracionesjs'] = False
        context['valoracionesTiendajs'] = False
        context['normal_footer_cat'] = True

        return render(request, 'nn.html', context)


class CondicionesView(View):

     def get(self, request, *args, **kwargs):
        context={}
        context['is_home'] = False
        context['lazyjs'] = False
        context['valoracionesjs'] = False
        context['valoracionesTiendajs'] = False
        context['normal_footer_cat'] = True

        return render(request, 'terms.html', context)

def subscribe(request):
    if request.method == 'POST':
        email = request.POST['email']
        email_qs = Subscribe.objects.filter(email_id=email)
        if email_qs.exists() or len(email)==0:
            data = {"status" : "404"}
            return JsonResponse(data)
        else:
            Subscribe.objects.create(email_id=email)
            SendSubscribeMail(email) # Send the Mail, Class available in utils.py
    return HttpResponse("/")

def successView(request):
        context={}
        context['is_home'] = True
        context['lazyjs'] = False
        context['valoracionesjs'] = False
        context['valoracionesTiendajs'] = False
        context['normal_footer_cat'] = True

        return render(request, 'success.html', context)

def neural(request):	
	if request.method == "POST":
	    file = request.FILES['file']
	    df = pd.read_csv(file)
	    df_target = df
	    lon = len(list(df.head(0)))
	    dim = len(list(df.head(0))) -1	
	    header = list(df[0:lon])
	    target = header[dim]
	    y = np.array(df[target])
	    df.drop(target,axis=1,inplace=True)
	    X = df.values
	    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3,random_state=101) 
	    graph_div = ''
	    pred = ''
	    red = request.POST['red']
	    dense = int(request.POST['dense'])	
	    epochs = int(request.POST['epochs'])
	    batch = int(request.POST['batch'])
	    #nodes = int(request.POST['categories'])
	    if red == 'Binary Cross-Entropy':
			    model= Sequential()
			    model.add(Dense(dense, input_dim=dim, activation='relu'))
			    model.add(Dense(dim, activation='relu'))
			    model.add(Dense(1, activation='sigmoid'))
			    model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
			    model.fit(x=X_train,y=y_train,batch_size=batch, epochs=epochs,shuffle=True)
			    pred = model.predict(X_test)	
			    _, accuracy = model.evaluate(X_test, y_test)			    
			    accu = (accuracy*100)
			    resultados = []
			    for i in pred:
		                    resultados.append(i[0])	
			    with open('/var/www/trainyourmodel/static/pred.csv', 'w', ) as myfile:
				    wr = csv.writer(myfile, quoting=csv.QUOTE_ALL)
				    for word in resultados:
					    wr.writerow([word])	
			    context = {'accu': accu, 'pred': pred}           
			    return render(request, "neural.html", context)						
	    if red == 'Mean Squared Error':
			    model = Sequential()
			    model.add(Dense(dense, input_dim=dim, activation='relu'))
			    model.add(Dense(1, activation='linear'))
			    model.compile(loss='mean_squared_error', optimizer='adam', metrics=['accuracy'])
			    model.fit(x=X,y=y,batch_size=batch, epochs=epochs,shuffle=True)
			    pred = model.predict(X_test)
			    _, accuracy = model.evaluate(X_test, y_test)
			    resultados = []
			    for i in pred:
		                    resultados.append(i[0])	
			    with open('/var/www/trainyourmodel/static/pred.csv', 'w', ) as myfile:
				    wr = csv.writer(myfile, quoting=csv.QUOTE_ALL)
				    for word in resultados:
					    wr.writerow([word])
			    accu = (accuracy*100)	
			    context = {'accu': accu, 'pred': pred}           
			    return render(request, "neural.html", context)
	    #if red == 'Multi-Class Cross-Entropy': 
	#		    model = Sequential() 
	#                   model.add(Dense(dense, input_dim=dim, activation='relu'))
	#		    model.add(Dense(nodes, activation='softmax'))
	#		    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
	#		    model.fit(x=X_train,y=y_train,batch_size=batch, epochs=epochs,shuffle=True)
	#		    _, accuracy = model.evaluate(X_test, y_test)
	#		    accu = ('Accuracy: %.2f' % (accuracy*100))
	#		    context = {'accu': accu}           
	#		    return render(request, "neural.html", context)
				  	       		      
			       	
def upload_csv(request):	
	if request.method == "POST":
	    file = request.FILES['csv_file']
	    df = pd.read_csv(file)
	    t = []
	    names = list(df.head(0))
	    df_target = df
	    grafica = request.POST['graficas']
	    if request.POST['submit'] == '_plot': 
	        if grafica == "scatter":
		        fig = px.scatter_matrix(df_target)
		        graph_div = plotly.offline.plot(fig, auto_open = False, output_type="div")
		        context = {'graph_div': graph_div}

templates/apriori.html
{% load extra_tags %}
<html> 
  <body style="background-color:#E4FDE1";"font size: 5";font-style: verdana";"align: center";>
  <h4>These are the association rules found by Apriori Algorithm:</h4>
  {{ rules }}
  </body>
</html>

templates/base.html
{% load static %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en-US">
<head profile="http://gmpg.org/xfn/11">
<head style="background-color:white;">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta name="viewport" content="width=device-width,initial-scale=1.0, user-scalable=no">
<link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,900|Oswald:300,400,500,600,700" rel="stylesheet">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
<link href="{% static 'semantic/dist/semantic.min.css' %}" rel="stylesheet">
<link rel="stylesheet" href="{% static 'trainyourmodel/css/style.css' %}" type="text/css" media="screen" />
<link rel="shortcut icon" href="{% static 'images/favicon/favicon.png' %}" type="image/x-icon">
<link rel="icon" href="{% static 'images/favicon/favicon.png' %}" type="image/x-icon">
<link rel="apple-touch-icon" sizes="60x60" href="{% static 'images/favicon/logo-feedmedata.png' %}">
<link rel="icon" type="image/png" sizes="192x192"  href="{% static 'images/favicon/logo-feedmedata.png' %}">
  
<link rel="icon" type="image/png" sizes="32x32" href="{% static 'images/favicon/favicon-32x32.png' %}">
<link rel="manifest" href="{% static 'images/favicon/manifest.json' %}">
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="msapplication-TileImage" content="{% static 'images/favicon/favicon.png' %}">
<title>{% block title %}Machine Learning as a Service 5{% endblock %}</title>
<script src="{% static 'trainyourmodel/js/jquery-3.3.1.min.js' %}"></script>
{% if is_home %}
  <script src="{% static 'trainyourmodel/js/owl.carousel.min.js' %}"></script>
{% endif %}
</head>
<body>  
<body style="background-color:white;">  
{% block content %}{% endblock %} 
{% comment %}<!-- footer -->{% endcomment %}
</body>  
<footer id="footer">
  <div class="main">
    <div class="container">
      <div class="main-1">
        <ul align = "left">
          <li><a href="https://www.trainyourmodel.com/how-it-works/" rel="nofollow">How trainyourmodel works</a></li>
          <li><a href="https://www.linkedin.com/in/jose-ruiz-05a563206/" rel="nofollow">Contact Me</a></li>
        </ul>
      </div>
      <div class="main-2">
      </div>
    </div>
  <div class="copy">
  <a href="#" class="scroll-top"></a>
</footer>
{% comment %}<!-- tab newsletter -->{% endcomment %}

{% comment %}<!-- ./tab newsletter -->{% endcomment %}
<link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.1.0/cookieconsent.min.css" />
<script src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.1.0/cookieconsent.min.js"></script>
<script>
window.addEventListener("load", function(){
window.cookieconsent.initialise({
  "palette": {
    "popup": {
      "background": "#3d3f4a",
      "text": "#ffffff"
    },
    "button": {
      "background": "#88c59f",
      "text": "#ffffff"
    }
  },
  "theme": "classic",
  "content": {
    "message": "ef successView(request):
        context={}

        context['is_home'] = True
        context['lazyjs'] = False
        context['valoracionesjs'] = False
        context['valoracionesTiendajs'] = False
        context['normal_footer_cat'] = True

        return render(request, 'success.html', context).",
    "dismiss": "Agree",
    "link": "Read more",
    "href": "https://www.trainyourmodel.com/privacy/"
  }
})});
</script>
<script src="{% static 'semantic/dist/semantic.min.js' %}"></script>
<script src="{% static 'trainyourmodel/js/animatescroll.min.js' %}"></script>
{% comment %}<script src="{% static 'trainyourmodel/js/jquery.fancybox.min.js' %}"></script>{% endcomment %}
<script src="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js"></script>
<script src="{% static 'trainyourmodel/js/icheck.js' %}"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/rateYo/2.3.2/jquery.rateyo.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/rateYo/2.3.2/jquery.rateyo.min.js"></script>
{% if lazyjs %}
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery.lazy/1.7.4/jquery.lazy.min.js"></script>
{% endif %}
<script src="{% static 'trainyourmodel/js/scripts.js' %}"></script>
<script src="{% static 'django_evercookie/swfobject-2.2.min.js' %}"></script>
<script src="{% static 'trainyourmodel/js/js.cookie.js' %}"></script>
<script src="/ecookie"></script>
{% if lazyjs %}
<script>
    $(function() {
        $('.lazy').lazy();
    });
    var $windowheight = $(window).outerHeight ();
    $('#search-container .results').css('max-height', $windowheight - 150);
    
    $( window ).resize(function() {
    $windowheight = $(window).outerHeight ();
    $('#search-container .results').css('max-height', $windowheight - 150);
  });
  
  $( window ).on( "orientationchange", function() {
    $windowheight = $(window).outerHeight ();
      $('#search-container .results').css('max-height', $windowheight - 150);
  });
</script>
{% endif %}
{% if is_home %}
<script>
    $('.slider-home').owlCarousel({
      autoplay: true,
      items: 1,
      loop: true,
      autoplayTimeout: 3000,
      smartSpeed: 350,
  });
</script>
{% endif %}    
{% block page_js %}
{% endblock %}
    </body>
<html/>

templates/contacto.html
{% extends "base.html" %}
{% load extra_tags %}
{% load static %}
{% block title %}Any inquiry? Get in touch!{% endblock %}
{% block meta %}
<meta name="description" content="If you have any doubt or question about Trainyourmodel, drop me an email.">
<meta property="og:title" content="¿Any doubt? Get in touch">
<meta property="og:site_name" content="Trainyourmodel">
<meta property="og:url" content="https://www.trainyourmodel.com/contact/">
<meta property="og:description" content="If you have any doubt or question about Trainyourmodel, drop me an email.">
<meta property="og:type" content="website" />
<meta property="og:image" content="/static/images/logo-feedmedata.jpg">
<meta property="og:locale" content="en_US" />
<link rel="canonical" href="https://www.trainyourmodel.com/contact/" />
<meta name="robots" content="noindex, follow">
{% endblock %}
{% block content %}
<body>	
	{% comment %}<!-- header -->{% endcomment %}
	<header id="header" class="ffixed">
		{% comment %}<!-- shared header -->{% endcomment %}
		{% include "header.html" %}
		{% comment %}<!-- ./shared header -->
		<!-- en background-image podemos sobreescribir la imagen -->{% endcomment %}
		<div class="head-bg" style="background-image: url({% static 'images/Logo-feedmedata.png' %}); background-position: 50% 90%">		
			<div class="title-tag-wrapper"><h1 class="title-tag">Contact</h1></div>
		</div>
	</header>
	{% comment %}<!-- ./header -->{% endcomment %}
	{% comment %}<!-- section section-text" -->{% endcomment %}
	<section class="section-text final-text">
		<div class="container small">
		<h2 class="tit1">How can I help?</h2>
		<p class="feat">Please feel free to reach out for any inquiry. I will try to respond asap.</p>
		</div>
		<div class="container xsmall contact-form">
			<form action="/contact/" method="post">
				{% csrf_token %}
				<div class="f-row">
					<label for="name">Name</label>
					<input type="text" id="name" name="name" required  />
				</div>
				<div class="f-row">
					<label for="email">Email</label>
					<input type="email" id="email_contacto" name="email_contacto" required />
				</div>
				<div class="f-row">
					<label for="message">Type your inquiry</label>
					<textarea id="message" name="message" required ></textarea>
				</div>
				
				<div class="f-row">
					<input type="submit" value="Send" class="btn" />
				</div>
			</form>
		</div>
	</section>
	{% comment %}<!-- ./section section-text" -->
	<!-- section -->{% endcomment %}
	<section class="section-text">
		<div class="container small">
		</div>
	</section>
	{% comment %}<!-- ./section -->{% endcomment %}
{% endblock %}

templates/funciona.html
{% extends "base.html" %}
{% load extra_tags %}
{% load static %}
{% block meta %}
<meta name="description" content="How does it work?">
<meta property="og:site_name" content="Trainyourmodel">
<meta property="og:url" content="www.trainyourmodel.com/">
<meta property="og:description" content="how it works">
<meta property="og:type" content="website" />
<meta property="og:image" content="/static/images/Logo-feedmedata.png">
<meta property="og:locale" content="en_US" />
<link rel="canonical" href="https://www.trainyourmodel.com" />
<meta name="robots" content="index, follow">
{% endblock %}
{% block content %}
<body class="home" style="background-color:#80ffbf; width:100%"> 
    <div id="top"></div>
    <header id="header-home" style="background-color:#80ffbf">    
        <div id="menu-mobile" style="background-color:#80ffbf;"></div>
            <div class="nav-home" style="background-color:#80ffbf;">
                <div class="logo"><a href="/"><img src="{% static 'images/logo-feedmedata.png' %}" alt="Logo feedmedata" width="100" height="53"/></a></div>
                <nav>
                    {% include "menu.html" %}
                </nav>
                <a href="#" class="toggle-menu">
                    <span class="bar"></span>
                    <span class="bar"></span>
                    <span class="bar"></span>
                </a>          
            </div>          
            </div> 
</header>   	
	
<section class="section-text como-funciona-intro">
    <h2 class="tit1">Machine Learning Made Easy</h2>
    <p class="feat"> Trainyourmodel is a free tool allowing to run machine learning algorithms in one click.
    <br><br>
    Just upload your data in csv format and place the target variable, if you have one, in the last column. 
    <br><br>
    Once you click run you will get results printed and a link to download predictions for your test data.
    <br><br>
    In general, you can use Unsupervised Algorithms to classify unlabeled data and find hidden patterns.
    <br><br>
    On the other hand, Supervised Algorithms need a labeled training dataset as input.<br> 
    </p>
</section>			
{% endblock %}

templates/header.html
{% load static %}
<div id="top" style="background-color:white;"></div>
<div class="menu-fix" style="background-color:white;">
	<div class="menu-nav" style="background-color:white;">
	        <div class="container" style="background-color:white;">
		<div class="logo-mobile"><a href="{% url 'portal:home' %}"><img src="{% static 'images/flaticon/logo-feedmedata.png' %}" alt="Logo The Best 5"/></a></div>
		<div class="nav">
			<nav>
				{% include "menu.html" %}
			</nav>
		</div>
		<a href="#" class="toggle-menu">
			<span class="bar"></span>
			<span class="bar"></span>
			<span class="bar"></span>
		</a>
		</div>
	</div>	
</div>

templates/heatmap.html
{% load extra_tags %}
<html> 
  <body style="background-color:#E4FDE1";"font size: 5";font-style: verdana";"align: center";>
  <h2>This is a heatmap showing correlations of each variable with all others and itself</h2>
  {{ graph_div|safe }}
  </body>
</html>

templates/index.html
<html>
  <head>
  <title>Feedmedata</title>
  </head>
  <body>
  <h1>hello this is from inde.hmtl</h1>
  {{ insert_me }}
  </body>
</html>

templates/kmeans.html
{% load extra_tags %}
{% load static %}

<html> 
  <body style="background-color:#E4FDE1";"font size: 5";font-style: verdana";"align: center";>
   <br><br>  
   <p> A csv file will be downloaded with one column having the predicted labels for each of your test items</p>                                                                                          
  <h2> These are the results for your dataset and selected algorithm</h2>
  <h4>Error vs Number of clusters:</h4>
  {{ graph|safe }}
 <p>The graph above shows how error decreases when a new cluster is added, you can pick the optimal number of clusters as the one in which the error drops significantly slower, then run the algorithm again with selected number of clusters</p> 
 <br><br>
                                                                                                                                                                                    
 <h4>Labels:</h4>
{{ labels }}
<p> <a href="{% static 'labels.csv' %}" download><font color="blue">Click Here To Download The Labels</font></a>  
</p>                                                                                     
</body>
</html>

templates/plottings.html
{% load extra_tags %}
<html> 
  <body style="background-color:#E4FDE1";"font size: 5";font-style: verdana";"align: center";>
  <h2>This is a scatter matrix showing correlation of each variable with all others and itself</h2>
  {{ graph_div|safe }}
  </body>
</html>

templates/priv.html
{% extends "base.html" %}
{% load extra_tags %}
{% load static %}
{% block title %}Privacy | Feedmedata{% endblock %}
{% block meta %}
<meta name="description" content="Statement of Privacy feedmedata.">
<meta property="og:title" content="Statement of Privacy | feedmedata">
<meta property="og:site_name" content="Feedmedata">
<meta property="og:url" content="{{request.build_absolute_uri}}">
<meta property="og:description" content="Statement of Privacy Feedmedata..">
<meta property="og:type" content="website" />
<meta property="og:image" content="{% static 'images/logo-feedmedata.png' %}">
<meta property="og:locale" content="en_US" />
<link rel="canonical" href="{{request.build_absolute_uri|to_https}}" />
<meta name="robots" content="noindex, follow">
{% endblock %}
{% block content %}
<body>	
	{% comment %}<!-- header -->{% endcomment %}
	<header id="header" class="fixed no-head-bg">
		{% comment %}<!-- shared header -->{% endcomment %}
		{% include "header.html" %}
		{% comment %}<!-- ./shared header -->{% endcomment %}
	</header>
	{% comment %}<!-- ./header -->{% endcomment %}
	<div class="container">
		{% comment %}<!-- section section-text -->{% endcomment %}
		<section class="section-text">
			<div class="container small">
				<h1 class="tit1">Private Policy</h1>
			</div>
			<div class="container small">
				<h2 class="tit3">Private Policy of Feedmedata</h2>
				<p>Through this privacy statement we inform you about that we do not collect your data nor have any intention to make a commercial use of your data.</p>
				<p>By using our website you confirm that you are of legal age. You will be able to visit www.feedmedata.me website without the site collecting or using your personal data.


</div>
{% endblock %}

templates/scatter.html
{% load extra_tags %}
{% load static %}

<html> 
  <body style="background-color:#E4FDE1";"font size: 5";font-style: verdana";"align: center";>
  <h2> These are the results for your dataset and selected algorithm</h2>
  <h4>Scatter Plot:</h4>
  <p>This graph plots the predictions generated by your model on the Y axis against the actual values in your test data on the X axis.</p>
   {{ scatter|safe }} 
   <br><br>
   <a href="{% static 'pred.csv' %}" download><font color="blue">Click Here To Download Your Model Predictions</font></a>  
   <br><br>
   <p> A csv file will be downloaded with one column having the predicted values for each of your test items</p>                                                            
   <h4>Mean Absolute Error:</h4>     {{ mae }}                                                                                     
   <h4>Mean Squared Error:</h4>      {{ mse }}   
   <h4>Root Mean Squared Error:</h4> {{ rmse }}  
   <h4>These are the coefficients for your features:</h4>  
   {{ coef }} 
   
                                                                                      
</html> 

templates/scatterplot.html
{% load extra_tags %}
<html> 
  <body style="background-color:#E4FDE1";"font size: 5";font-style: verdana";"align: center";>
  <h2>This is a scatter matrix showing correlation of each variable with all others and itself</h2>
  {{ graph_div|safe }}
  </body>
</html>

templates/terms.html
{% extends "base.html" %}
{% load extra_tags %}
{% load static %}
{% block title %}Terms and Conditions|Feedmedata {% endblock %}
{% block meta %}
<meta name="description" content="Terms and Conditions">
<meta property="og:title" content="Terms and Conditions |Feedmedata">
<meta property="og:site_name" content="Feedmedata">
<meta property="og:url" content="{{request.build_absolute_uri}}">
<meta property="og:description" content="Terms and Conditions.">
<meta property="og:type" content="website" />
<meta property="og:image" content="{% static 'images/Logo-feedmedata.png' %}">
<meta property="og:locale" content="en_US" />
<link rel="canonical" href="{{request.build_absolute_uri|to_https}}" />
<meta name="robots" content="noindex, follow">
{% endblock %}
{% block content %}
<body>
	<!-- header -->
	<header id="header" class="fixed no-head-bg">
		{% comment %}<!-- shared header -->{% endcomment %}
		{% include "header.html" %}
		{% comment %}<!-- ./shared header -->{% endcomment %}
	</header>
	{% comment %}<!-- ./header -->{% endcomment %}
	<div class="container">
		{% comment %}<!-- section section-text -->{% endcomment %}
		<section class="section-text">
			<div class="container small">
				<h1 class="tit1">Terms and Conditions</h1>
			</div>
			<div class="container small">
				<div class="box-feat">
					<p>IMPORTANT: YOU AGREE TO THE FOLLOWING TERMS AND CONDITIONS. IF YOU DO NOT ACCEPT THE TERMS DO NOT USE THIS WEBSITE.</p>
				</div>
				<h2 class="tit3">1. Please be aware...</h2>
				
				<p>That Feedmedata is an online tool to perform calculations. That means:</p>
				<ul>
					<li>· We are not responsible for the use you make of our tool.</li>
					<li>· We are not liable for the implications of your use of this tool.</li>
				        <li>· We don't sell your information.</li>
					<li>· We are not obligated to provide any service or satisfy any petition.</li>
				
       			</div>
		</section>
		{% comment %}<!-- ./section section-text -->{% endcomment %}
	</div>
{% endblock %}